# Frequently used and handy Numpy functions


### Let's dive into Numpy functions

Get to know Numpy... Numpy is an open-source library of Python for scientific computing and for working with arrays. It includes high-level mathematical and statistical functions. Below are frequently used functions of Numpy, which I find handy as well:

- np.linspace
- np.argmax
- np.char.equal
- np.nonzero
- np.polyval

Let's get introduced to these functions and its features.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations',
             git_message="git commit message")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained 
function1 = np.linspace
function2 = np.argmax
function3 = np.char.equal
function4 = np.nonzero
function5 = np.polyval

## Function 1 - np.linspace

**np.linspace** function returns _num_ evenly spaced numbers over the interval [start, stop]. If _num_ is not specified, by default num will be set to 50, i.e., num = 50. **np.linspace** is similar to Numpy **arange** function which uses step instead of number.

In [6]:
# Example 1

np.linspace(start = -2, stop = 2, num = 5, retstep = True)

(array([-2., -1.,  0.,  1.,  2.]), 1.0)

In above Example 1, np.linspace was used to create 1D array containing elements between -2 and 2 included with 5 evenly spaced numbers. It also returns step size 1.0 between consecutive numbers. Here, retstep set to True to return step size between consecutive numbers, otherwise, it set to False by default.

In [7]:
# Example 2

b = np.linspace((0,1),(2,3), num = 5, retstep = False, axis = 1)       # 2D array
print(b,'\n')
print('Shape of an array b while axis=1:', b.shape)

[[0.  0.5 1.  1.5 2. ]
 [1.  1.5 2.  2.5 3. ]] 

Shape of an array b while axis=1: (2, 5)


In above Example 2, 2D array was created containing numbers between [0,2] and [1,3] endpoints included with 5 evenly spaced numbers along axis=1, that is along columns. If axis is not specified, axis = 0 by default.

In [8]:
# Example 3 - breaking (to illustrate when it breaks)

np.linspace(0, 3, 11, axis = 1)

AxisError: destination: axis 1 is out of bounds for array of dimension 1

In above Example 3, there is an AxisError caused by axis=1, mismatch of dimensions. Error can be avoided by creating multidimentional array or by setting axis to zero for 1D arrays.

np.linspace can be used in graph plotting combined with other mathematical functions such as np.sin(), np.cos(), etc. Also, it can be used to generate samples for x-axis.

In [9]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "almashka/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/almashka/numpy-array-operations


'https://jovian.ml/almashka/numpy-array-operations'

## Function 2 - np.argmax

**np.argmax** function returns the indices of the maximum element of an array along a particular axis. If there are duplicates of maximum value, function gets the first encountered index of that value.

In [10]:
# Example 1

array1 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
np.argmax(array1)

8

In above Example 1, np.argmax function gets the index of the largest value in the array1. That is, number 9 with index 8.

In [11]:
# Example 2

array2 = np.array([[1,2,3],
                   [7,9,8]])
np.argmax(array2, axis=1)

array([2, 1])

In above Example 2, np.argmax function returns the index of maximum value along axis 1. That is, number 3 with index 2 and number 9 with index 1.

In [12]:
# Example 3 - breaking (to illustrate when it breaks)

np.argmax(np.linspace(1,64,8), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

Above Example 3, throws an error AxisError where the axis is out of bound. To fix it, keep default axis=0 since it is 1D array.

np.argmax can be used in reinforcement learning, machine learning, or simply to retrieve the highest value of an array through index.

In [13]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "almashka/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/almashka/numpy-array-operations


'https://jovian.ml/almashka/numpy-array-operations'

## Function 3 - np.char.equal

**np.char.equal** function compares texts (strings) character by character and returns boolean result. Used with string values only.

In [14]:
# Example 1

np.char.equal('apple','pineapple')

array(False)

In above Example 1, np.char.equal function compares words 'apple' and 'pineapple' letter by letter, then returns False since words are not equal.

In [15]:
# Example 2.1

greet1 = 'Hello World!'
greet2 = 'Hello world!'

np.char.equal(greet1, greet2)

array(False)

In above Example 2, np.char.equal function compares same messages and returns False. That is, because Python is case sensitive. Comparing string same-shaped arrays can be done as well, which will return boolean array for each compared array element, see below Example 2.2

In [16]:
# Example 2.2

text1 = np.array(['merhaba', 'hello','salem','hola'])
text2 = np.array(['merhaba', 'hi','salem','hola'])

np.char.equal(text1, text2)

array([ True, False,  True,  True])

In [17]:
# Example 3 - breaking (to illustrate when it breaks)

np.char.equal(34,'34')

TypeError: comparison of non-string arrays

Above Example 3, throws TypeError, that is, np.char.equal function works only with string data types. For this particular example, error can be avoided by rewriting function as np.char.equal('34','34').

np.char.equal function can be used to look up for identical elements in an array.

In [18]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "almashka/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/almashka/numpy-array-operations


'https://jovian.ml/almashka/numpy-array-operations'

## Function 4 - np.nonzero

**np.nonzero** function gets the indices of elements of an array that are not zero.

In [19]:
# Example 1 - 1D array

arr1 = np.linspace(-2,2,5)
print(arr1)
print('Indicex of nonzero elements:', np.nonzero(arr1))

[-2. -1.  0.  1.  2.]
Indicex of nonzero elements: (array([0, 1, 3, 4]),)


In above Example 1, np.nonzero function returns only indices 0,1,3 and 4, index 2 is skipped since number is 0.

In [20]:
# Example 2 - 2D array

arr2 = np.array([[1,2,0],
                 [7,0,5]])
np.nonzero(arr2)

(array([0, 0, 1, 1]), array([0, 1, 0, 2]))

In above Example 2, np.nonzero gets indices of nonzero values for each axis. That is, for axis=0 it gets 0,0,1,1 and for axis=1 it gets 0,1,0,2. It looks more clear from below indexing,<br>
                                       arr2 **[0]** [0] <br>
                                       arr2 **[0]** [1] <br>
                                       arr2 **[1]** [0] <br>
                                       arr2 **[1]** [2] <br>

In [21]:
# Example 3 - breaking (to illustrate when it breaks)

np.nonzero([1,2],[3,3])

TypeError: _nonzero_dispatcher() takes 1 positional argument but 2 were given

Above Example 3, gives a TypeError since two arguments were passed into a function. np.nonzero takes exactly one argument and it works for any data type. Above error can be avoided by passing one argument into np.nonzero.

np.nonzero function can be used to detect elements that satisfy certain condition in an array. For instance, to look up for NBA game scores above 60 for a certain year.

In [22]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "almashka/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/almashka/numpy-array-operations


'https://jovian.ml/almashka/numpy-array-operations'

## Function 5 - np.polyval

**np.polyval** function solves a polynomial at a specific value of x. Polynomial is passed as 1D array of polynomial coefficients in a standard form, i.e., polynomial terms are ordered from biggest exponent to lowest exponent.

In [23]:
# Example 1

np.polyval([2,-5,1,3], x = 2)

1

In above Example 1, np.polyval function finds the value of polynomial at x = 2. Polynomial is 2*(x^3) - 5*(x^2) + 1(x) + 3, find its value at x = 2. <br>
Solution: 2*(2^3) - 5*(2^2) + 1(2) + 3 = 16 - 20 + 2 + 3 = 1

In [24]:
# Example 2

np.polyval([4,0,1], 3)

37

In above Example 2, np.polyval finds the value of 4(x^2) + 1 at x = 3. Since polynomial is indeed as 4(x^2) + 0(x^1) + 1, we need to pass all coefficients of it in order to get the correct result.

In [25]:
# Example 3 - breaking (to illustrate when it breaks)

np.polyval([2,8,2],1,2)

TypeError: _polyval_dispatcher() takes 2 positional arguments but 3 were given

Above Example 3, throws an error since three arguments were passed into np.polyval function. It takes exactly two arguments, one for polynomial and one for x value. To fix this error, we should remove one of x values 1 or 2; or we can list them out if we want to check for each corresponding value of x as,<br>
np.polyval([2,8,2], [1,2]).<br>
Here, function will evaluate polynomail for both x = 1 and x = 2, and return result as an array.

np.polyval can be used in calculations of complex polynomials and in plotting graphs of polynomials. Frequently encountered combination of np.linspace and np.polyval in graph plotting.

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "almashka/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/almashka/numpy-array-operations


'https://jovian.ml/almashka/numpy-array-operations'

## Conclusion

In this notebook we have learned 5 frequently used and handy Numpy functions that are,
- np.linspace
- np.argmax
- np.char.equal
- np.nonzero
- np.polyval

These build-in functions of Numpy are time saving and practical to use. Mathematical and statistical calculations can be done on multidimensional arrays without using loops. Futher, we will learn about Pandas library and dataframes. Stay tuned!

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* 10 Numpy functions you should know : https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5
* Numpy official website : https://numpy.org/doc/stable/reference/routines.html

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
